### ISSUE TITLE
looking for appimage for version prior to 84. 

### ISSUE THREAD

**Issue by rebeltaz** [igorlogius/chromium-browser-appimage#1]
I don't suppose you have - or know where I can get - an appimage for chromium prior to version 84? I need a version that supports TLS/SSL 1.0.

**Comment by igorlogius** [comment]
No, sorry, i dont know where you could get an appimage of those versions.  
But you could maybe find an old binary (either to use or to create an appimage manually with).
Take a look here: 
https://www.chromium.org/getting-involved/download-chromium/#downloading-old-builds-of-chrome-chromium

Hope it helps.

**Comment by rebeltaz** [comment]
I appreciate that. Thanks.

**Comment by igorlogius** [comment]
This might also be useful for you:  
- https://gist.github.com/probonopd/3d5d045619e3ff239b0a43406d75cd2e
Good luck.
