### ISSUE TITLE
How to build locally for Thorium.

### ISSUE THREAD

**Issue by Alex313031** [igorlogius/chromium-browser-appimage#2]
@igorlogius  Hi, I'm working on a Chromium fork for Linux, Windows, Raspi, and MacOS called Thorium > https://thorium.rocks/ & https://github.com/Alex313031/Thorium

I currently offer .deb and portable .zips for linux releases, but I would like to make an appimage. How would I do this locally, I.E. not using github actions but just using libappimage or pkg2appimage here on my machine?

**Comment by igorlogius** [comment]
This => https://gist.github.com/probonopd/3d5d045619e3ff239b0a43406d75cd2e
should contain most of the required information you'll need. 

Hope it helps.
